services:
  - type: web
    name: alpha-md
    env: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm run keith
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SKIP_WA_CONNECTION
        value: "true"
    autoDeploy: true
    plan: free
