services:
  - type: web
    name: alpha-md
    env: node
    build:
      dockerfile: Dockerfile
    start: npm run keith
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
