services:
  - type: web
    name: alpha-md
    env: node
    build:
      dockerfile: Dockerfile
    startCommand: node server.js
    healthCheckPath: /health
    healthCheckTimeout: 60
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
    plan: free
